#服务端口
server:
  port: 9002
#spring配置
spring:
  application:
    name: ihrm_system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://175.24.111.52:3306/ihrm?useUnicode=true&characterEncoding=utf8
    username: root
    password: centos
  jpa:
    hibernate:
      ddl-auto: update
    database: MySql
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
jwt:
  config:
    ttl: 3600000
    key: ihrm